# Generated by Django 6.0 on 2025-12-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('CONTRACTOR', 'Contractor')], default='STAFF', max_length=20),
        ),
    ]
