# Generated by Django 6.0 on 2025-12-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0002_employee_employment_status_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Employee hire date', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='Probation end date', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_start_date',
            field=models.DateField(blank=True, help_text='Probation start date', null=True),
        ),
    ]
