# Generated by Django 6.0 on 2025-12-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0006_position_employee_position_and_more'),
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ID', 'ID / Passport'), ('RESUME', 'Resume'), ('CONTRACT', 'Contract'), ('ADDENDUM', 'Addendum'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('identifier', models.CharField(blank=True, help_text='Document number / identifier', max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr_core.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='platform_core.organization')),
            ],
            options={
                'verbose_name': 'Employee document',
                'verbose_name_plural': 'Employee documents',
                'constraints': [models.CheckConstraint(condition=models.Q(('file__isnull', False), ('url__isnull', False), _connector='OR'), name='employee_document_file_or_url')],
            },
        ),
    ]
