# Generated by Django 6.0 on 2025-12-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='platform_core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PLATFORM', 'Platform'), ('TIME_TRACKING', 'Time Tracking'), ('HR', 'HR Core'), ('LEAVE', 'Absences'), ('PAYROLL', 'Payroll'), ('ORG_STRUCTURE', 'Org Structure')], max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='platform_core.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
